version: "3.0"

services:
  postgres:
    image: "postgres:13"
    container_name: "my_postgres"
    environment:
      POSTGRES_USER: "akshat"
      POSTGRES_PASSWORD: "pgpass"
      POSTGRES_DB: "pgsql_db_chatapp"
    ports:
      - "5555:5432"
    volumes:
      - backend_my_dbdata:/var/lib/postgresql/data
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
volumes:
  backend_my_dbdata: